sudo: false
language: python
cache:
  directories:
    - "$HOME/.cache/pip"
services:
  - mysql
env:
  - DATABASE=mysql DATABASE_USER=travis DATABASE_PASSWORD=
  - DATABASE=sqlite
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install: pip install -U pip tox-travis
script: tox
