sudo: false
language: python
cache: pip
services:
  - mysql
env:
  - DATABASE=mysql DATABASE_USER=travis DATABASE_PASSWORD=
  - DATABASE=sqlite
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
install:
  - pip install -U pip
  - pip install 'tox>=3.4.0' tox-travis codecov
script: tox -vv -r
after_success: codecov -e TRAVIS_PYTHON_VERSION -e DATABASE
